### PR TITLE
Fix batch mode for scijava commands that return a Dataset.

### LINKED ISSUE #215: IJ2 commands returning Dataset/Img don't work with setBatchMode(true) in macros
Consider the following macro, using the *File > Import > Image...* command:

```javascript
#@ File input
setBatchMode(true);
run("Image... ", "source=[" + input +"] crop=false autoscale=true computeminmax=false x=0 y=0 w=0 h=0 groupfiles=false mode=Auto range=0");
run("Z Project...", "projection=[Max Intensity] all");
setBatchMode("show");
```

This will throw and error:

> There are no images open in line 4

Changing line 2 to `setBatchMode(false);` makes it work as expected.

I guess the issue is that `Dataset` objects are not (or too lazily) synced with IJ1 `ImagePlus`es.

### PR DESCRIPTION
**Pull request by maarzt**
* Add a test to check if a scijava command behaves as expected in batch
  mode.
* Tiny change to the method `rebuildImagePlusData` in the class `Harmonizer`.

fixes #215

### CODE REVIEW

**Comment by maarzt** [comment]
@hinerm Thank you for the hint.
The newly added tests were failing, as the expect an graphics environment. I added an the junit assumption and now its fine.

Is it ready to be merged?

File: src/test/java/net/imagej/legacy/BatchModeTest.java [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+	static {
+		LegacyInjector.preinit();
+	}
+
+	private Context context;
+
+	@Before
+	public void setUp() {
+		// only run the tests if a graphics environment is present
+		assumeFalse(GraphicsEnvironment.isHeadless());
```
Comment (imagejan) [inline src/test/java/net/imagej/legacy/BatchModeTest.java:41]: Shouldn't running a macro work *the same* whether or not in headless mode? If it fails in headless, it's a bug (either here or in `ij1-patcher`), no?

Comment (maarzt) [reply src/test/java/net/imagej/legacy/BatchModeTest.java]: A macro should run the same way, if headless in batch mode or with UI. But that's currently not the case. This PR fixes only a small part of the problem. A macro running in batch mode will now have access to the output images of a scijava command. But this works only if the legacy UI is visible.
